/**
 * MOBILE RANKING PARITY GATE
 * ==========================
 *
 * This is a correctness gate, not a unit test. It proves that mobile's OWN
 * TypeScript ranking port (`src/lib/algorithms.ts` + `src/lib/restaurants.ts`)
 * produces the EXACT SAME default ranking as the precomputed web summary
 * (`apps/web/data/summary.json`), which was generated by the SHARED web
 * ranking-core at the default settings.
 *
 * The web side already proves `summary == web browser render`
 * (apps/web/scripts/verify_ranking_parity.mjs). This test closes the loop on
 * the mobile side: `summary == mobile computeRecommendations` at default.
 *
 * IMPORTANT: Do NOT weaken the comparison to make it pass. If the two diverge,
 * that is a real product bug — the two surfaces would rank cards differently.
 * The failure messages below print the first diverging entry on both sides so
 * the divergence is diagnosable.
 *
 * Default settings (must match how summary.json was generated):
 *   selectedCity = scope, orderValue = 10000, outingsPerWeek = 1,
 *   no filters, eligibility off.
 */

import fs from "fs";
import path from "path";

import { computeRecommendations } from "@/lib/algorithms";
import { computeRestaurantDeals } from "@/lib/restaurants";
import { buildDealCardKey } from "@/lib/format";
import { buildEstimatesByTier } from "@/lib/eligibility";
import {
  AlgorithmState,
  Offer,
  OffersBundle,
  OffersIndex,
  RequirementMapping,
  RequirementRecord,
  RequirementsPack,
  RestaurantEnrichment,
} from "@/types";

// The web data directory is the single source of truth for both surfaces.
const DATA_DIR = path.resolve(__dirname, "../../web/data");

const SCOPES = ["all", "karachi", "lahore", "islamabad"] as const;
type Scope = (typeof SCOPES)[number];

function readJson<T>(relOrAbs: string): T {
  const full = path.isAbsolute(relOrAbs) ? relOrAbs : path.join(DATA_DIR, relOrAbs);
  return JSON.parse(fs.readFileSync(full, "utf8")) as T;
}

/**
 * Loads the offers bundle the same way mobile's runtime `loadOffers` does:
 * read the index, concat each city file's `.offers`, and attach the
 * restaurants enrichment. (Runtime also merges inferred_cuisines for the
 * long-tail, but that only affects cuisine FILTERING, which is off at default,
 * so it cannot change the default ranking. We mirror it anyway for fidelity.)
 */
function loadOffersBundle(): OffersBundle {
  const index = readJson<OffersIndex>("offers-index.json");

  const offers: Offer[] = [];
  for (const city of index.cities) {
    const rel = index.cityFiles[city];
    if (!rel) continue;
    const cityFile = readJson<{ offers: Offer[] }>(path.basename(rel));
    offers.push(...(cityFile.offers || []));
  }

  const restaurantsEnrichment: Record<string, RestaurantEnrichment> = {};
  if (index.restaurantsFile) {
    const r = readJson<{ restaurants: Record<string, RestaurantEnrichment> }>(
      path.basename(index.restaurantsFile)
    );
    Object.assign(restaurantsEnrichment, r.restaurants || {});
  }
  try {
    const inferred = readJson<{ restaurants: Record<string, string[]> }>(
      "inferred_cuisines.json"
    );
    for (const [name, cuisines] of Object.entries(inferred.restaurants || {})) {
      if (!Array.isArray(cuisines) || cuisines.length === 0) continue;
      if (!restaurantsEnrichment[name]) {
        restaurantsEnrichment[name] = { servesCuisine: cuisines };
      }
    }
  } catch {
    // optional file
  }

  return {
    generatedAt: index.generatedAt,
    dayNames: index.dayNames,
    offers,
    restaurantsEnrichment,
    stats: index.stats,
  };
}

/**
 * Builds the RequirementsPack EXACTLY as mobile's runtime `loadRequirements`
 * does (src/data/index.ts): byCardId keyed on card_id, mappingByDealKey keyed
 * via buildDealCardKey(deal_bank_name, deal_card_name), estimatesByTier via
 * buildEstimatesByTier. We reuse mobile's own helpers so the key normalization
 * is byte-identical to runtime.
 *
 * NOTE: at default `useEligibility` is false and salary/balance are null, so
 * eligibility never filters or shifts the ranking. But computeFeePenalty reads
 * `requirementStatus.annualFeePkr` / `annualFeeWaiverRule` / hasRequirementRecord,
 * which DO depend on this pack — so it must be built faithfully.
 */
function loadRequirementsPack(): RequirementsPack {
  const records = readJson<RequirementRecord[]>(
    "card-requirements/normalized/card_requirements.json"
  );
  const rawMap = readJson<
    | RequirementMapping[]
    | { mappings: RequirementMapping[] }
  >("card-requirements/normalized/deal_requirement_card_map.json");

  const byCardId = new Map<string, RequirementRecord>();
  records.forEach((r) => byCardId.set(r.card_id, r));

  const list = Array.isArray(rawMap) ? rawMap : rawMap.mappings;
  const mappingByDealKey = new Map<string, RequirementMapping>();
  list.forEach((m) => {
    const row = m as unknown as {
      deal_bank_name?: string;
      deal_card_name?: string;
      matched?: boolean;
      requirement_card_id?: string;
    };
    if (!row.deal_bank_name || !row.deal_card_name) return;
    const key = buildDealCardKey(row.deal_bank_name, row.deal_card_name);
    mappingByDealKey.set(key, {
      deal_card_key: key,
      matched: !!row.matched,
      requirement_card_id: row.requirement_card_id ?? null,
    });
  });

  return {
    available: true,
    byCardId,
    mappingByDealKey,
    estimatesByTier: buildEstimatesByTier(records),
  };
}

/** The default AlgorithmState for a given scope (matches summary generation). */
function defaultState(
  scope: Scope,
  data: OffersBundle,
  requirements: RequirementsPack
): AlgorithmState {
  return {
    data,
    requirements,
    selectedCity: scope, // "all" | "karachi" | "lahore" | "islamabad"
    selectedDays: new Set<number>(),
    selectedRestaurants: new Set<string>(),
    selectedBanks: new Set<string>(),
    selectedCardTypes: new Set<string>(),
    selectedCards: new Set<string>(),
    selectedCuisines: new Set<string>(),
    orderValue: 10000,
    useEligibility: false,
    monthlySalary: null,
    accountBalance: null,
    outingsPerWeek: 1,
    ownedCards: new Set<string>(),
    walletSize: 2,
    walletBuildOnOwned: false,
    walletMaxFee: null,
    walletNoSameBank: false,
    walletMixedTypes: false,
    walletObjective: "savings",
    walletMustInclude: new Set<string>(),
    favoriteRestaurants: new Set<string>(),
  };
}

interface SummaryCardEntry {
  bank: string;
  card: string;
  score: number;
}
interface SummaryRestaurantEntry {
  restaurant: string;
  city: string;
  saving: number;
}
interface Summary {
  scopes: Record<string, SummaryCardEntry[]>;
  restaurantDeals: Record<string, SummaryRestaurantEntry[]>;
}

// Load everything once. The data files are large; building per-scope is cheap.
const bundle = loadOffersBundle();
const reqs = loadRequirementsPack();
const summary = readJson<Summary>("summary.json");

const cardSig = (e: { bank: string; card: string; score: number }) =>
  `${e.bank}||${e.card}|${e.score.toFixed(4)}`;
const restSig = (e: { city: string; restaurant: string; saving: number }) =>
  `${e.city}||${e.restaurant}|${e.saving.toFixed(4)}`;

/** Asserts two signature arrays are identical, reporting the first divergence. */
function assertSignaturesEqual(
  label: string,
  mobileSigs: string[],
  webSigs: string[]
) {
  const n = Math.min(mobileSigs.length, webSigs.length);
  for (let i = 0; i < n; i++) {
    if (mobileSigs[i] !== webSigs[i]) {
      throw new Error(
        `${label}: first divergence at index ${i}\n` +
          `  mobile[${i}] = ${mobileSigs[i]}\n` +
          `  web   [${i}] = ${webSigs[i]}\n` +
          `  (mobile length ${mobileSigs.length}, web length ${webSigs.length})`
      );
    }
  }
  if (mobileSigs.length !== webSigs.length) {
    const longer = mobileSigs.length > webSigs.length ? "mobile" : "web";
    const extra =
      mobileSigs.length > webSigs.length
        ? mobileSigs.slice(n)
        : webSigs.slice(n);
    throw new Error(
      `${label}: lists agree on the first ${n} entries but lengths differ ` +
        `(mobile ${mobileSigs.length}, web ${webSigs.length}). ` +
        `Extra entries in ${longer}: ${extra.slice(0, 5).join(", ")}${
          extra.length > 5 ? " …" : ""
        }`
    );
  }
}

describe("Mobile ranking parity gate (mobile port vs web summary, default settings)", () => {
  describe.each(SCOPES)("scope: %s", (scope) => {
    test("computeRecommendations matches summary.scopes order + score", () => {
      const state = defaultState(scope, bundle, reqs);
      const ranked = computeRecommendations(state);

      const webEntries = summary.scopes[scope];
      expect(Array.isArray(webEntries)).toBe(true);

      const mobileSigs = ranked.map(cardSig);
      const webSigs = webEntries.map(cardSig);

      assertSignaturesEqual(`[${scope}] card ranking`, mobileSigs, webSigs);
      // Belt-and-suspenders: identical length + identical full arrays.
      expect(mobileSigs.length).toBe(webSigs.length);
      expect(mobileSigs).toEqual(webSigs);
    });

    test("computeRestaurantDeals matches summary.restaurantDeals order + saving", () => {
      const state = defaultState(scope, bundle, reqs);
      const deals = computeRestaurantDeals(state);

      const webDeals = summary.restaurantDeals[scope];
      expect(Array.isArray(webDeals)).toBe(true);

      // Mobile returns `bestSaving`; summary stores `saving`. Normalize.
      const mobileSigs = deals.map((d) =>
        restSig({ city: d.city, restaurant: d.restaurant, saving: d.bestSaving })
      );
      const webSigs = webDeals.map(restSig);

      assertSignaturesEqual(
        `[${scope}] restaurant deals`,
        mobileSigs,
        webSigs
      );
      expect(mobileSigs.length).toBe(webSigs.length);
      expect(mobileSigs).toEqual(webSigs);
    });
  });
});
